### ISSUE TITLE
Remaining v1 tasks

### ISSUE THREAD

**Issue by chloerice** [chloerice/wbb-3.0#24]
## Build out v1 sitemap with layouts
- Footer
  - Links
      - [x] Donate (set up same way as in navbar) (#25)
      - [x] Hire
      - [x] Partner
      - [x] Volunteer
    - [x] Subscribe input => Subscribe button (#26)
- Navbar (#7 )
    - Links
      - [x] Home (wordmark)
      - [x] About
      - [x] Get involved
          - [x] Events
            - [x] Mavens I/O
            - [x] Meetups
          - [x] Programs
            - [x] Bounty Board
          - [x] Slack
      - [x] Make an impact
          - [x] Hire
          - [x] Partner
          - [x] Volunteer
      - [x] Donate 
  - `/`
    - DEVELOPMENT
      - [x] Change hero to be image + overlay instead background image
      - [x] Change carousel layout to grid (#14)
    - IMAGES
      - [x] Hero
      - [x] Callouts (2) (#32)
    ~Full width image block (#33)~
      - [x] Get involved grid (Slack, Meetups, Mavens, Bounty Board) (#34)
    - CONTENT
      - [x] Intro
      - [x] Callouts
  - `/about`
    - DEVELOPMENT
      - [x] "Where we're headed" content block (#27)
    - CONTENT
      - [x] Our story hero
      - [x] Where we're headed blurb (#30)
      - [x] Bio blurbs for current team (Adam, Kris, Dev, Me) (#28)
    - IMAGES
        - [x] Headshots of current team (Adam, Kris, Dev, Me) (#29)
        - [x] Founders (group photos)
  - `/get-involved`
    - `/events` 
      - `/meetups`
        - DEVELOPMENT
          - [x] Simple checkered grid layout (content image image content) below hero (#13) 
      - `/mavens-conference`
          - [x] Hero
          - [x] Callout section: goals + images
          - [x] 2019 Recap video embed
          - [x] Call to action block (volunteer, partner)
      - [x] `/slack`
    - [x] `/programs`
      - [x] `/bounty-board` (just Google form link for v1)
  - `/make-an-impact`
    - `/hire` (v1 just link to Google form)
      - [x] FORM
    - `/partner`
      - [x] FORM
      - IMAGES
        - [x] Swag shot
        - [x] Partner logos
      - CONTENT
        - [x] Hero
        - [x] Benchmarks (*polish*) (#31)
        - [x] Call to action block (link to form)
    - `/volunteer` 
      - [x] v1 just link direct to Google form
- DEPLOYMENT
  - [x] Ship to Netlify (set up CI/CD) 
  - [x] `netlify.toml` redirects to forms
